import os
import uuid
import logging

from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
import yt_dlp

app = Flask(__name__)

# Allow requests from your GitHub Pages website.
FRONTEND_ORIGIN = "https://k1rankumarreddy.github.io"

CORS(
    app,
    resources={
        r"/api/*": {
            "origins": [FRONTEND_ORIGIN],
            "methods": ["GET", "POST", "OPTIONS"],
            "allow_headers": ["Content-Type"],
        }
    },
)

app.config["MAX_CONTENT_LENGTH"] = 1024 * 1024

logging.basicConfig(level=logging.INFO)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DOWNLOAD_FOLDER = os.path.join(BASE_DIR, "downloads")

os.makedirs(DOWNLOAD_FOLDER, exist_ok=True)


def detect_platform(url):
    url = url.lower()

    if "youtube.com/" in url or "youtu.be/" in url:
        return "YouTube"

    if "instagram.com/" in url:
        return "Instagram"

    return None


@app.route("/", methods=["GET"])
def home():
    return jsonify({
        "status": "running",
        "service": "Personal Video Downloader",
        "message": "Backend is working."
    })


@app.route("/api/health", methods=["GET"])
def health():
    return jsonify({
        "status": "ok"
    })


@app.route("/api/video", methods=["POST", "OPTIONS"])
def get_video():

    # Respond to the browser's CORS preflight.
    if request.method == "OPTIONS":
        return "", 204

    data = request.get_json(silent=True)

    if not data:
        return jsonify({
            "error": "Please send a valid JSON request."
        }), 400

    url = data.get("url", "").strip()

    if not url:
        return jsonify({
            "error": "Please provide a video URL."
        }), 400

    platform = detect_platform(url)

    if not platform:
        return jsonify({
            "error": "Only YouTube and Instagram URLs are supported."
        }), 400

    video_id = str(uuid.uuid4())

    output_template = os.path.join(
        DOWNLOAD_FOLDER,
        video_id + ".%(ext)s"
    )

    options = {
        "outtmpl": output_template,
        "format": "best[ext=mp4]/best",
        "noplaylist": True,
        "quiet": True,
        "no_warnings": True,
        "restrictfilenames": True,
        "max_filesize": 100 * 1024 * 1024,
        "socket_timeout": 30,
        "retries": 1,
    }

    try:
        with yt_dlp.YoutubeDL(options) as downloader:
            info = downloader.extract_info(
                url,
                download=True
            )

        filename = next(
            (
                name
                for name in os.listdir(DOWNLOAD_FOLDER)
                if name.startswith(video_id + ".")
            ),
            None
        )

        if not filename:
            return jsonify({
                "error": "The downloaded video file could not be found."
            }), 500

        return jsonify({
            "success": True,
            "title": info.get("title", "Video"),
            "platform": platform,
            "video_url": "/api/video-file/" + filename
        })

    except Exception:
        app.logger.exception("Video retrieval failed")

        return jsonify({
            "error": (
                "Unable to retrieve this video. "
                "Check the URL and ensure the content is accessible."
            )
        }), 400


@app.route(
    "/api/video-file/<path:filename>",
    methods=["GET", "OPTIONS"]
)
def video_file(filename):

    if request.method == "OPTIONS":
        return "", 204

    # Only serve files generated by this application.
    if os.path.basename(filename) != filename:
        return jsonify({
            "error": "Invalid filename."
        }), 400

    if not filename.startswith(tuple(
        name.split(".")[0]
        for name in os.listdir(DOWNLOAD_FOLDER)
    )):
        return jsonify({
            "error": "File not found."
        }), 404

    return send_from_directory(
        DOWNLOAD_FOLDER,
        filename,
        as_attachment=False
    )


if __name__ == "__main__":
    port = int(os.environ.get("PORT", "8080"))

    app.run(
        host="0.0.0.0",
        port=port
    )
